---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

Attempting some benchmarking on looping vs map/apply. The simple function that returns NULL is from this stack overflow comparing map and lapply.

https://stackoverflow.com/questions/45101045/why-use-purrrmap-instead-of-lapply

```{r}
library(purrr)
library(bench)
n <- 1e4
x <- 1:n
f <- function(x) NULL
g <- function(x) NA

# unallocated list NULL
lf <- function(x) {
  out <- vector(mode = "list")
  for (i in x) {
    out[i] <- list(f(i))
  }
  out
}

# allocated list NULL
laf <- function(x) {
  out <- vector(mode = "list", length = length(x))
  for (i in x) {
    out[i] <- list(f(i))
  }
  out
}

# unallocated list NA
lfna <- function(x) {
  out <- vector(mode = "list")
  for (i in x) {
    out[i] <- g(i)
  }
  out
}

# allocated list NA
lafna <- function(x) {
  out <- vector(mode = "list", length = length(x))
  for (i in x) {
    out[i] <- g(i)
  }
  out
}
```

Bench::marks. For some reason, naming my expressions isn't working. 

```{r}
mark(applyNULL = lapply(x, f), 
     mapNULL  = map(x, f),
     loopNULL  = lf(x),
     loop_allocNULL  = laf(x))

mark(applyNA = lapply(x, g), 
     mapNA  = map(x, g),
     loopNA  = lfna(x),
     loop_allocNA  = lafna(x))
```

